version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sist_log
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: sist_log
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: sist_log_app
    restart: always
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: