services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sist_log
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: sist_log
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sist_log_app
    restart: always
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: sist_log
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    depends_on:
      mysql:
        condition: service_healthy
        required: true

volumes:
  mysql_data: